fileVersion: 1
id: "69"
mappingDefinitions:
  DESTINATION:
    database: ben-dev
    schema: trash
  SOURCE:
    database: coalesce
    schema: sample_data
  TRASH:
    database: ben-dev
    schema: trash
name: New Environment
type: Environment
