fileVersion: 1
id: "72"
mappingDefinitions:
  DESTINATION:
    database: ben-dev
    schema: default
  SOURCE:
    database: coalesce
    schema: sample_data
  TRASH:
    database: ben-dev
    schema: trash
name: New Environment
type: Environment
